### ISSUE TITLE
[BUG] wu platform #Error in linux virtual machine getting hardware info

### ISSUE THREAD

**Issue by dridon** [Sable/wu-wei-benchmarking-toolkit#19]
wu platform gives me the following issue:

-- Please give a short name to your computer
-- (For example, mbp-2011 / win-user / linux-fans)
Enter name: fuzzy
Traceback (most recent call last):
File "/usr/lib/node_modules/wu-wei-benchmarking-toolkit/bin/platform", line 157, in 
prettyPrint(getInfo())
File "/usr/lib/node_modules/wu-wei-benchmarking-toolkit/bin/platform", line 7, in getInfo
info = getHardwareInfo()
File "/usr/lib/node_modules/wu-wei-benchmarking-toolkit/bin/platform", line 57, in getHardwareInfo
info.append(getLinuxGPU()); # [3]
File "/usr/lib/node_modules/wu-wei-benchmarking-toolkit/bin/platform", line 98, in getLinuxGPU
res.append(trimB(line,'controller:','('))
File "/usr/lib/node_modules/wu-wei-benchmarking-toolkit/bin/platform", line 72, in trimB
end = s.index(endop,sta)
ValueError: substring not found

**Comment by elavoie** [comment]
Closed by #23
