### ISSUE TITLE
Error in the function help

### ISSUE THREAD

**Issue by wukefe** [Sable/wu-wei-benchmarking-toolkit#40]
Minor error when using `wu report help`.  Supposedly, it should return help messages if there is any possible use for this command.

```shell
hanfeng.c@sableintel $ wu report help
fs.js:1000
  binding.stat(pathModule._makeLong(path), statValues);
          ^

Error: ENOENT: no such file or directory, stat '/home/sable/hanfeng.c/experiment/ecoop18/wu-wei-benchmarking-toolkit/bin/help'
    at Error (native)
    at Object.fs.statSync (fs.js:1000:11)
    at Object.<anonymous> (/home/sable/hanfeng.c/experiment/ecoop18/wu-wei-benchmarking-toolkit/bin/wu:48:19)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:389:7)
```

**Comment by wukefe** [comment]
The same error for `wu run help`

**Comment by elavoie** [comment]
Usage is ````wu help run```` or ````wu run -h```` or ````wu run --help````. ;-)
